using System;
using System.Collections.Generic;
using Server.Items;
using Server.Mobiles;

namespace Server.Custom.AIGM.Characters.Waylander
{
    public static partial class WaylanderRosterCatalog
    {
        private static IEnumerable<WaylanderCharacterDefinition> BuildBook1Definitions()
        {
            List<WaylanderCharacterDefinition> list = new List<WaylanderCharacterDefinition>();

            WaylanderCharacterDefinition dakeyras = Allied(Def("dakeyras", "dakeyras", "book1", "Dakeyras", "the grey killer", "Independent Drenai", "Assassin / protector"));
            dakeyras.Aliases = new[] { "waylander", "the grey man", "gentleman", "dak" };
            dakeyras.Body = 0x190;
            dakeyras.Hue = Utility.RandomSkinHue();
            dakeyras.HairItemId = 0x203B;
            dakeyras.HairHue = 1109;
            dakeyras.FacialHairItemId = 0x2041;
            dakeyras.FacialHairHue = 1109;
            dakeyras.Str = 100;
            dakeyras.Dex = 110;
            dakeyras.Int = 80;
            dakeyras.Hits = 180;
            dakeyras.DamageMin = 11;
            dakeyras.DamageMax = 16;
            dakeyras.VirtualArmor = 32;
            dakeyras.Fame = 7000;
            dakeyras.Karma = -500;
            dakeyras.IdentityLine = "I am Dakeyras. Some call me Waylander. The name matters less than whether I keep those under my care alive.";
            dakeyras.WaylanderLine = "Waylander is the name men use when they want the killer and not the man.";
            dakeyras.FactionLine = "I do not wear another man's colors. I keep faith with promises, not banners.";
            dakeyras.PhilosophyLine = "Redemption is built in choices. Mercy and killing both turn rotten when pride touches them.";
            dakeyras.DefaultReplyLine = "Ask what matters and I will give you the clean edge of it.";
            dakeyras.FactionKeywords = new[] { "drenai", "vagrian", "nadir" };
            dakeyras.PhilosophyKeywords = new[] { "redemption", "mercy", "promise", "guilt" };
            dakeyras.EnemyIds = new[] { "kaem", "kesa_khan", "morak", "zhu_chao" };
            dakeyras.Relationships.Add(Rel("danyal", "spouse", "guarded tenderness", 98, "Danyal is his wife and moral equal.", WaylanderRelationshipTimelineState.Current, "Danyal is my wife. She sees through the armor and has earned the right.", null));
            dakeyras.Relationships.Add(Rel("miriel", "adopted_child", "protective pride", 96, "Miriel is his adopted daughter and trained warrior.", WaylanderRelationshipTimelineState.Current, "Miriel is my daughter by choice and by training. I taught her to survive, and that burden cuts both ways.", null));
            dakeyras.Relationships.Add(Rel("krylla", "adopted_child", "protective", 95, "Krylla is his adopted daughter.", WaylanderRelationshipTimelineState.Current, "Krylla deserved peace more than any legend. I would rather guard that than hear my own name praised.", null));
            dakeyras.Relationships.Add(Rel("dardalion", "ally", "respectful restraint", 85, "Dardalion is a rescued priest and moral challenge.", WaylanderRelationshipTimelineState.Current, "Dardalion has courage enough to keep his conscience. Men like that are rare.", null));
            dakeyras.Relationships.Add(Rel("kaem", "betrayer", "cold hatred", 10, "Kaem hired him and betrayed him.", WaylanderRelationshipTimelineState.Historical, "Kaem bought a kingdom's death and believed coin would bury the price. He was wrong.", null));
            Fact(dakeyras, "cadoras", "Cadoras was a killer with a code. I respected him more than many decent men.");
            Fact(dakeyras, "durmast", "Durmast sold us once, then died proving a man can still choose rightly at the end.");
            Fact(dakeyras, "karnak", "Karnak is useful, clever, and never half as foolish as he sounds.");
            Fact(dakeyras, "orien", "Orien asked the hardest thing a father can ask: to trust the man who killed his son.");
            dakeyras.EquipAction = delegate (WaylanderRosterMobile mobile) { EquipWaylanderLeathers(mobile, false); };
            Skill(dakeyras, SkillName.Archery, 110.0);
            Skill(dakeyras, SkillName.Fencing, 100.0);
            Skill(dakeyras, SkillName.Stealth, 95.0);
            Skill(dakeyras, SkillName.Hiding, 95.0);
            Skill(dakeyras, SkillName.Tactics, 100.0);
            Skill(dakeyras, SkillName.Anatomy, 95.0);
            list.Add(dakeyras);

            WaylanderCharacterDefinition dardalion = Allied(Def("dardalion", "dardalion", "warrior_priest", "Dardalion", "founder of the Thirty", "The Source / The Thirty", "Warrior-priest"));
            dardalion.Aliases = new[] { "source priest", "founder of the thirty" };
            dardalion.Body = 0x190;
            dardalion.Hue = Utility.RandomSkinHue();
            dardalion.HairItemId = 0x203C;
            dardalion.HairHue = 1150;
            dardalion.FacialHairItemId = 0x203F;
            dardalion.FacialHairHue = 1150;
            dardalion.Str = 95;
            dardalion.Dex = 80;
            dardalion.Int = 95;
            dardalion.Hits = 170;
            dardalion.DamageMin = 9;
            dardalion.DamageMax = 14;
            dardalion.VirtualArmor = 36;
            dardalion.Fame = 6500;
            dardalion.Karma = 6000;
            dardalion.IdentityLine = "I am Dardalion, once a priest who believed purity meant distance from violence. I learned better at terrible cost.";
            dardalion.WaylanderLine = "Waylander is the man who rescued me and forced me to ask whether innocence without courage is only vanity.";
            dardalion.FactionLine = "I stand with the Source and with the Thirty, not to celebrate violence, but to prevent evil from ruling by default.";
            dardalion.PhilosophyLine = "Mercy without courage can become a polished form of surrender. Duty means accepting stain when life must be defended.";
            dardalion.DefaultReplyLine = "Ask plainly. I would rather answer honestly than comfort you with fog.";
            dardalion.FactionKeywords = new[] { "source", "the thirty", "brotherhood" };
            dardalion.PhilosophyKeywords = new[] { "faith", "mercy", "violence", "duty", "source" };
            dardalion.EnemyIds = new[] { "zhu_chao", "innicas", "dark_brotherhood_knight" };
            dardalion.Relationships.Add(Rel("dakeyras", "ally", "grateful respect", 88, "Waylander rescued him and remained his moral challenge.", WaylanderRelationshipTimelineState.Current, "Waylander saved my life. I honor him too much to lie about his darkness or his decency.", null));
            dardalion.Relationships.Add(Rel("danyal", "ally", "warm respect", 82, "Danyal is a trusted ally.", WaylanderRelationshipTimelineState.Current, "Danyal speaks with the courage of a clear heart. She has steadied more than one dangerous man.", null));
            dardalion.Relationships.Add(Rel("innicas", "faction_enemy", "holy enmity", 5, "Innicas leads the Dark Brotherhood in the field.", WaylanderRelationshipTimelineState.Future, "Innicas turns discipline into an engine for spiritual rot. Men like him must be opposed without hesitation.", "Book 1 Dardalion should not casually know Innicas unless scenario time allows."));
            Fact(dardalion, "regnak", "Regnak belongs to a later age unless the world has chosen to fold time in on itself.");
            dardalion.EquipAction = delegate (WaylanderRosterMobile mobile) { EquipThirtyArmor(mobile, false); };
            Skill(dardalion, SkillName.Swords, 105.0);
            Skill(dardalion, SkillName.Parry, 95.0);
            Skill(dardalion, SkillName.Healing, 100.0);
            Skill(dardalion, SkillName.SpiritSpeak, 95.0);
            Skill(dardalion, SkillName.Meditation, 90.0);
            Skill(dardalion, SkillName.MagicResist, 90.0);
            list.Add(dardalion);

            WaylanderCharacterDefinition danyal = Allied(Def("danyal", "danyal", "book1", "Danyal", "Waylander's wife", "Waylander's household", "Protector / survivor"));
            danyal.Body = 0x191;
            danyal.Female = true;
            danyal.Hue = Utility.RandomSkinHue();
            danyal.HairItemId = 0x203B;
            danyal.HairHue = 0x66D;
            danyal.Str = 85;
            danyal.Dex = 95;
            danyal.Int = 80;
            danyal.Hits = 150;
            danyal.DamageMin = 7;
            danyal.DamageMax = 11;
            danyal.VirtualArmor = 24;
            danyal.Fame = 4500;
            danyal.Karma = 2500;
            danyal.IdentityLine = "I am Danyal. I have seen fear closely enough to stop admiring men who hide behind it.";
            danyal.WaylanderLine = "Waylander is my husband, and no, I do not confuse love with blindness.";
            danyal.FactionLine = "My side is my family and the people who still need protecting.";
            danyal.PhilosophyLine = "Courage is a choice made while your hands still shake. Anything easier is just vanity in a brave coat.";
            danyal.DefaultReplyLine = "You will get the truth from me, not a soft version of it.";
            danyal.Relationships.Add(Rel("dakeyras", "spouse", "fierce love", 98, "Waylander is her husband and moral equal.", WaylanderRelationshipTimelineState.Current, "Waylander is my husband. I know what he has done and what he still chooses to protect.", null));
            danyal.Relationships.Add(Rel("miriel", "adopted_child", "protective pride", 96, "Miriel is her adopted daughter.", WaylanderRelationshipTimelineState.Current, "Miriel is my daughter. She was not shaped to stay helpless for anyone's comfort.", null));
            danyal.Relationships.Add(Rel("krylla", "adopted_child", "protective", 96, "Krylla is her adopted daughter.", WaylanderRelationshipTimelineState.Current, "Krylla deserved a life that war nearly stole. I guard that possibility fiercely.", null));
            danyal.Relationships.Add(Rel("dardalion", "ally", "trusted warmth", 82, "Dardalion is a trusted priest and ally.", WaylanderRelationshipTimelineState.Current, "Dardalion has more courage than many men who brag about steel.", null));
            Fact(danyal, "kai", "Kai was gentler than the world deserved, and kinder than most pretty-faced men.");
            Fact(danyal, "durmast", "Durmast made himself hard to trust. His last choice mattered anyway.");
            danyal.EquipAction = delegate (WaylanderRosterMobile mobile)
            {
                Wear(mobile, new Boots(), null, 0);
                Wear(mobile, new FancyShirt(), "Traveller's Blouse", 0x66D);
                Wear(mobile, new LeatherChest(), "Traveller's Jerkin", 0x846);
                Wear(mobile, new LeatherArms(), null, 0x846);
                Wear(mobile, new LeatherGloves(), null, 0x846);
                Wear(mobile, new LeatherLegs(), null, 0x846);
                Wear(mobile, new Dagger(), "Training Blade", 0x66D);
            };
            Skill(danyal, SkillName.Fencing, 82.0);
            Skill(danyal, SkillName.Archery, 75.0);
            Skill(danyal, SkillName.Healing, 70.0);
            Skill(danyal, SkillName.Tactics, 78.0);
            list.Add(danyal);

            WaylanderCharacterDefinition durmast = Neutral(Def("durmast", "durmast", "book1", "Durmast", "the guide", "Independent / Vagrian-paid", "Guide / rogue"));
            durmast.Body = 0x190;
            durmast.Hue = Utility.RandomSkinHue();
            durmast.HairItemId = 0x203B;
            durmast.HairHue = 0x455;
            durmast.FacialHairItemId = 0x203F;
            durmast.FacialHairHue = 0x455;
            durmast.Str = 90;
            durmast.Dex = 85;
            durmast.Int = 70;
            durmast.Hits = 145;
            durmast.DamageMin = 9;
            durmast.DamageMax = 13;
            durmast.VirtualArmor = 24;
            durmast.IdentityLine = "Durmast. Guide, rogue, survivor. Take the order you like least and it will usually be the truest.";
            durmast.WaylanderLine = "Waylander was employer, victim, and in the end the one man I chose not to sell all the way through.";
            durmast.FactionLine = "I served whoever paid until the price soured in my mouth.";
            durmast.PhilosophyLine = "A man learns what he cannot sell only when the bargain finally reaches his own throat.";
            durmast.DefaultReplyLine = "If you want something clean, ask a priest. If you want it true, ask again.";
            durmast.Relationships.Add(Rel("dakeyras", "betrayer", "ashamed respect", 40, "Waylander was his employer and the man he betrayed before choosing redemption.", WaylanderRelationshipTimelineState.Historical, "Waylander had every reason to leave me to my own filth. He did not.", null));
            durmast.Relationships.Add(Rel("danyal", "ally", "wary respect", 30, "Danyal distrusted him.", WaylanderRelationshipTimelineState.Historical, "Danyal saw what I was quicker than most. She was not wrong.", null));
            durmast.EnemyIds = new[] { "kaem" };
            durmast.EquipAction = delegate (WaylanderRosterMobile mobile)
            {
                Wear(mobile, new Boots(), null, 0);
                Wear(mobile, new Shirt(), null, 0x59B);
                Wear(mobile, new LeatherChest(), "Guide's Jerkin", 0x59B);
                Wear(mobile, new DurmastWarAxe(), null, -1);
                Pack(mobile, new Dagger(), "Spare Trail Knife", 0x59B);
            };
            Skill(durmast, SkillName.Swords, 92.0);
            Skill(durmast, SkillName.Tactics, 88.0);
            Skill(durmast, SkillName.Hiding, 60.0);
            list.Add(durmast);

            WaylanderCharacterDefinition cadoras = Neutral(Def("cadoras", "cadoras", "book1", "Cadoras", "the stalker", "Independent", "Assassin / archer"));
            cadoras.Body = 0x190;
            cadoras.Hue = Utility.RandomSkinHue();
            cadoras.HairItemId = 0x2048;
            cadoras.HairHue = 0x497;
            cadoras.Str = 90;
            cadoras.Dex = 105;
            cadoras.Int = 75;
            cadoras.Hits = 155;
            cadoras.DamageMin = 10;
            cadoras.DamageMax = 15;
            cadoras.VirtualArmor = 28;
            cadoras.IdentityLine = "Cadoras. If you have heard the name, you already know I dislike cheap shots and cheap men equally.";
            cadoras.WaylanderLine = "Waylander was a contract I refused to handle cheaply, then a rival worth saving.";
            cadoras.FactionLine = "I serve my code before I serve any banner or purse.";
            cadoras.PhilosophyLine = "A profession without a code belongs to the highest bidder. I preferred to belong to myself.";
            cadoras.Relationships.Add(Rel("dakeyras", "rival", "professional respect", 80, "Waylander was his target and rival.", WaylanderRelationshipTimelineState.Historical, "Waylander was worth the shot I never took. That tells you enough.", null));
            cadoras.EquipAction = delegate (WaylanderRosterMobile mobile)
            {
                Wear(mobile, new Boots(), null, 0);
                Wear(mobile, new LeatherChest(), "Stalker's Jack", 0x497);
                Wear(mobile, new LeatherArms(), null, 0x497);
                Wear(mobile, new LeatherGloves(), null, 0x497);
                Wear(mobile, new CadorasStalkerBow(), null, -1);
                Pack(mobile, new Dagger(), "Close Blade", 0x497);
            };
            Skill(cadoras, SkillName.Archery, 105.0);
            Skill(cadoras, SkillName.Fencing, 88.0);
            Skill(cadoras, SkillName.Hiding, 70.0);
            list.Add(cadoras);

            WaylanderCharacterDefinition karnak = Allied(Def("karnak", "karnak", "book1", "Karnak", "General Karnak", "Drenai", "Commander / warrior"));
            karnak.Body = 0x190;
            karnak.Hue = Utility.RandomSkinHue();
            karnak.HairItemId = 0x203C;
            karnak.HairHue = 0x8A5;
            karnak.FacialHairItemId = 0x2041;
            karnak.FacialHairHue = 0x8A5;
            karnak.Str = 110;
            karnak.Dex = 90;
            karnak.Int = 95;
            karnak.Hits = 190;
            karnak.DamageMin = 12;
            karnak.DamageMax = 18;
            karnak.VirtualArmor = 38;
            karnak.IdentityLine = "Karnak. General, survivor, and far less foolish than men find convenient.";
            karnak.WaylanderLine = "Waylander is useful, dangerous, and not the sort of asset you store in a box marked simple.";
            karnak.FactionLine = "I serve the survival of the Drenai, and I prefer to remain essential while doing it.";
            karnak.PhilosophyLine = "Politics is another battlefield. If a nation lives because fools underestimated you, thank the fools and keep moving.";
            karnak.Relationships.Add(Rel("egel", "ally", "professional respect", 78, "Egel is his fellow commander.", WaylanderRelationshipTimelineState.Current, "Egel carries duty like a blade kept clean. I respect that, even when it irritates me.", null));
            karnak.Relationships.Add(Rel("waylander", "ally", "calculated respect", 65, "Waylander is a dangerous asset.", WaylanderRelationshipTimelineState.Current, "Waylander is useful because he dislikes ceremony even more than I do.", null));
            karnak.Relationships.Add(Rel("miriel", "enemy", "fatal enmity", 10, "Miriel later kills Karnak in revenge.", WaylanderRelationshipTimelineState.Future, "Miriel belongs to a grief that will one day sharpen into steel.", "Book 1 Karnak should not know the exact future without scenario time-folding."));
            Fact(karnak, "bodalen", "Bodalen is my son. Legacy is another battlefield, and a nastier one.");
            karnak.EquipAction = delegate (WaylanderRosterMobile mobile)
            {
                Wear(mobile, new Boots(), null, 0);
                Wear(mobile, new FancyShirt(), "General's Shirt", 0x8A5);
                Wear(mobile, new PlateChest(), "Karnak's Plate", 0x8A5);
                Wear(mobile, new PlateArms(), null, 0x8A5);
                Wear(mobile, new PlateGloves(), null, 0x8A5);
                Wear(mobile, new PlateLegs(), null, 0x8A5);
                Wear(mobile, new KarnakSilverAxe(), null, -1);
            };
            Skill(karnak, SkillName.Swords, 105.0);
            Skill(karnak, SkillName.Tactics, 105.0);
            Skill(karnak, SkillName.Anatomy, 95.0);
            list.Add(karnak);

            WaylanderCharacterDefinition egel = Allied(Def("egel", "egel", "book1", "Egel", "Earl of Bronze", "Drenai", "Commander"));
            egel.Body = 0x190;
            egel.Hue = Utility.RandomSkinHue();
            egel.HairItemId = 0x203B;
            egel.HairHue = 0x59C;
            egel.FacialHairItemId = 0x2041;
            egel.FacialHairHue = 0x59C;
            egel.Str = 105;
            egel.Dex = 85;
            egel.Int = 90;
            egel.Hits = 185;
            egel.DamageMin = 11;
            egel.DamageMax = 16;
            egel.VirtualArmor = 42;
            egel.IdentityLine = "I am Egel, called Earl of Bronze. Nations are not kept alive by vanity, so I have no time for it.";
            egel.WaylanderLine = "Waylander is not a man I would choose lightly, which is precisely why he matters.";
            egel.FactionLine = "I stand for the Drenai and for the walls future generations will need after we are bones.";
            egel.PhilosophyLine = "Command is stewardship. If glory gets soldiers killed, it deserves contempt rather than applause.";
            egel.Relationships.Add(Rel("karnak", "ally", "measured respect", 76, "Karnak is his fellow commander and political contrast.", WaylanderRelationshipTimelineState.Current, "Karnak is loud enough for three men and clever enough for six. We have made use of both facts.", null));
            egel.Relationships.Add(Rel("dardalion", "ally", "respectful trust", 80, "Dardalion advises him spiritually.", WaylanderRelationshipTimelineState.Current, "Dardalion remembers that a nation's soul matters even while its walls are being built. I value that.", null));
            egel.EquipAction = delegate (WaylanderRosterMobile mobile)
            {
                Wear(mobile, new Boots(), null, 0);
                Wear(mobile, new ArmourOfBronze_Chest(), null, -1);
                Wear(mobile, new ArmourOfBronze_Arms(), null, -1);
                Wear(mobile, new ArmourOfBronze_Gloves(), null, -1);
                Wear(mobile, new ArmourOfBronze_Helm(), null, -1);
                Wear(mobile, new ArmourOfBronze_Legs(), null, -1);
                Wear(mobile, new Longsword(), "Bronze Earl's Sword", 2213);
            };
            Skill(egel, SkillName.Swords, 102.0);
            Skill(egel, SkillName.Tactics, 105.0);
            Skill(egel, SkillName.Parry, 95.0);
            list.Add(egel);

            WaylanderCharacterDefinition gellan = Allied(Def("gellan", "gellan", "book1", "Gellan", "the officer", "Drenai", "Officer"));
            gellan.Body = 0x190;
            gellan.Hue = Utility.RandomSkinHue();
            gellan.HairItemId = 0x203B;
            gellan.HairHue = 0x6B8;
            gellan.Str = 90;
            gellan.Dex = 85;
            gellan.Int = 75;
            gellan.Hits = 150;
            gellan.DamageMin = 8;
            gellan.DamageMax = 13;
            gellan.VirtualArmor = 30;
            gellan.IdentityLine = "Gellan. I held the line where I was told and kept what should stay unsaid.";
            gellan.WaylanderLine = "Waylander was Dakeyras before the world made harsher use of him. I never forgot that.";
            gellan.FactionLine = "Drenai. Soldier first, ornament never.";
            gellan.PhilosophyLine = "Loyalty is often the discipline to keep silent about what would cost a comrade his life.";
            gellan.Relationships.Add(Rel("dakeyras", "ally", "quiet loyalty", 84, "He knows Dakeyras's identity and never exposed it.", WaylanderRelationshipTimelineState.Historical, "I knew Dakeyras when his name was still plain. That was enough for me.", null));
            gellan.Relationships.Add(Rel("jonat", "commander", "trust", 72, "Jonat follows him in command.", WaylanderRelationshipTimelineState.Historical, "Jonat's tongue is bitter because he keeps seeing the same stupid mistakes. He still does the work.", null));
            gellan.EquipAction = delegate (WaylanderRosterMobile mobile)
            {
                Wear(mobile, new Boots(), null, 0);
                Wear(mobile, new RingmailChest(), "Officer's Cuirass", 0x6B8);
                Wear(mobile, new RingmailArms(), null, 0x6B8);
                Wear(mobile, new RingmailGloves(), null, 0x6B8);
                Wear(mobile, new RingmailLegs(), null, 0x6B8);
                Wear(mobile, new Broadsword(), null, 0x6B8);
                Wear(mobile, new HeaterShield(), null, 0x6B8);
            };
            Skill(gellan, SkillName.Swords, 85.0);
            Skill(gellan, SkillName.Tactics, 88.0);
            list.Add(gellan);

            WaylanderCharacterDefinition jonat = Allied(Def("jonat", "jonat", "book1", "Jonat", "the bitter officer", "Drenai", "Officer"));
            jonat.Body = 0x190;
            jonat.Hue = Utility.RandomSkinHue();
            jonat.HairItemId = 0x203C;
            jonat.HairHue = 0x455;
            jonat.Str = 88;
            jonat.Dex = 82;
            jonat.Int = 82;
            jonat.Hits = 148;
            jonat.DamageMin = 8;
            jonat.DamageMax = 12;
            jonat.VirtualArmor = 28;
            jonat.IdentityLine = "Jonat. Competence without patience for decorated fools.";
            jonat.WaylanderLine = "Waylander is proof that the dangerous man is sometimes the necessary one.";
            jonat.FactionLine = "Drenai, though I have met enough noble idiots to make the word taste bitter some days.";
            jonat.PhilosophyLine = "Rank does not create wisdom. Soldiers pay in blood whenever cowards mistake inheritance for ability.";
            jonat.Relationships.Add(Rel("gellan", "ally", "loyal respect", 78, "Gellan was his predecessor.", WaylanderRelationshipTimelineState.Historical, "Gellan kept men alive without needing applause. I respected that.", null));
            jonat.Relationships.Add(Rel("karnak", "ally", "wary respect", 62, "Karnak is a capable superior he watches carefully.", WaylanderRelationshipTimelineState.Current, "Karnak is useful because he knows theater is a weapon, not because I enjoy the performance.", null));
            jonat.EquipAction = delegate (WaylanderRosterMobile mobile)
            {
                Wear(mobile, new Boots(), null, 0);
                Wear(mobile, new RingmailChest(), "Officer's Cuirass", 0x455);
                Wear(mobile, new RingmailArms(), null, 0x455);
                Wear(mobile, new RingmailLegs(), null, 0x455);
                Wear(mobile, new Broadsword(), null, 0x455);
            };
            Skill(jonat, SkillName.Swords, 84.0);
            Skill(jonat, SkillName.Tactics, 86.0);
            list.Add(jonat);

            WaylanderCharacterDefinition sarvaj = Allied(Def("sarvaj", "sarvaj", "book1", "Sarvaj", "the steady officer", "Drenai", "Officer / stabilizer"));
            sarvaj.Body = 0x190;
            sarvaj.Hue = Utility.RandomSkinHue();
            sarvaj.HairItemId = 0x2049;
            sarvaj.HairHue = 0x59B;
            sarvaj.Str = 86;
            sarvaj.Dex = 84;
            sarvaj.Int = 78;
            sarvaj.Hits = 150;
            sarvaj.DamageMin = 8;
            sarvaj.DamageMax = 12;
            sarvaj.VirtualArmor = 28;
            sarvaj.IdentityLine = "Sarvaj. I am usually the man keeping frightened soldiers from breaking apart.";
            sarvaj.WaylanderLine = "Waylander fights like a man who has already paid for the right to be tired.";
            sarvaj.FactionLine = "Drenai. A unit survives because someone keeps the frightened men from feeling alone.";
            sarvaj.PhilosophyLine = "Courage is often borrowed. If your calm lets another man hold, you have done real work.";
            sarvaj.Relationships.Add(Rel("gellan", "ally", "steady loyalty", 82, "Gellan is his commander and friend.", WaylanderRelationshipTimelineState.Historical, "Gellan was the kind of commander men remember because they stayed alive beneath him.", null));
            sarvaj.Relationships.Add(Rel("jonat", "ally", "trust", 74, "Jonat is his fellow officer.", WaylanderRelationshipTimelineState.Current, "Jonat growls because he keeps seeing the same errors. He is still worth standing beside.", null));
            sarvaj.EquipAction = delegate (WaylanderRosterMobile mobile)
            {
                Wear(mobile, new Boots(), null, 0);
                Wear(mobile, new RingmailChest(), "Field Cuirass", 0x59B);
                Wear(mobile, new RingmailArms(), null, 0x59B);
                Wear(mobile, new RingmailLegs(), null, 0x59B);
                Wear(mobile, new Broadsword(), null, 0x59B);
                Wear(mobile, new HeaterShield(), null, 0x59B);
            };
            Skill(sarvaj, SkillName.Swords, 82.0);
            Skill(sarvaj, SkillName.Tactics, 84.0);
            list.Add(sarvaj);

            WaylanderCharacterDefinition kaem = Hostile(Def("kaem", "kaem", "book1", "Kaem", "Vagrian general", "Vagrian", "Commander / antagonist"));
            kaem.Body = 0x190;
            kaem.Hue = Utility.RandomSkinHue();
            kaem.HairItemId = 0x203C;
            kaem.HairHue = 0x444;
            kaem.FacialHairItemId = 0x203F;
            kaem.FacialHairHue = 0x444;
            kaem.Str = 105;
            kaem.Dex = 85;
            kaem.Int = 95;
            kaem.Hits = 185;
            kaem.DamageMin = 11;
            kaem.DamageMax = 17;
            kaem.VirtualArmor = 36;
            kaem.IdentityLine = "I am Kaem. Men who lose kingdoms to sentiment usually die under them.";
            kaem.WaylanderLine = "Waylander was a hired blade who forgot a tool should never live long enough to resent the hand that used it.";
            kaem.FactionLine = "Vagrian command. Authority survives when weakness is punished before it spreads.";
            kaem.PhilosophyLine = "Results bury hesitation. Regret is only useful when it sharpens vengeance.";
            kaem.Relationships.Add(Rel("dakeyras", "betrayer", "vengeful hatred", 0, "Waylander killed Niallad for him and was later betrayed.", WaylanderRelationshipTimelineState.Historical, "Waylander did the work, then mistook survival for freedom.", null));
            Fact(kaem, "niallad", "Niallad was a king whose death reshaped more than a border.");
            kaem.EnemyIds = new[] { "dakeyras", "danyal" };
            kaem.EquipAction = delegate (WaylanderRosterMobile mobile)
            {
                Wear(mobile, new Boots(), null, 0);
                Wear(mobile, new PlateChest(), "Vagrian Command Plate", 0x444);
                Wear(mobile, new PlateArms(), null, 0x444);
                Wear(mobile, new PlateGloves(), null, 0x444);
                Wear(mobile, new PlateLegs(), null, 0x444);
                Wear(mobile, new Longsword(), null, 0x444);
            };
            Skill(kaem, SkillName.Swords, 100.0);
            Skill(kaem, SkillName.Tactics, 102.0);
            list.Add(kaem);

            WaylanderCharacterDefinition orien = Allied(Def("orien", "orien", "book1", "Orien", "former king", "Drenai", "Founder / elder"));
            orien.Body = 0x190;
            orien.Hue = Utility.RandomSkinHue();
            orien.HairItemId = 0x2048;
            orien.HairHue = 0x47E;
            orien.FacialHairItemId = 0x2041;
            orien.FacialHairHue = 0x47E;
            orien.Str = 70;
            orien.Dex = 60;
            orien.Int = 100;
            orien.Hits = 135;
            orien.DamageMin = 6;
            orien.DamageMax = 10;
            orien.VirtualArmor = 18;
            orien.IdentityLine = "Orien. I founded a nation, buried a son, and learned that grief does not absolve a king from thinking clearly.";
            orien.WaylanderLine = "Waylander murdered my son and still became the man I needed. That is not forgiveness. It is strategy hardened by duty.";
            orien.FactionLine = "Drenai, though I learned long ago that a nation outlives the pride of any one king.";
            orien.PhilosophyLine = "Power that cannot yield when duty demands it has already become vanity.";
            orien.Relationships.Add(Rel("niallad", "parent", "grief", 100, "Niallad is his son.", WaylanderRelationshipTimelineState.Deceased, "Niallad was my son. Kingship does not thin that grief.", null));
            orien.Relationships.Add(Rel("dakeyras", "ally", "grave necessity", 60, "Waylander killed his son and later served his kingdom.", WaylanderRelationshipTimelineState.Historical, "Waylander is the hardest kind of instrument to use: one with a conscience and blood already on it.", null));
            orien.EquipAction = delegate (WaylanderRosterMobile mobile)
            {
                Wear(mobile, new Sandals(), null, 0);
                Wear(mobile, new Shirt(), "Doeskin Tunic", 0x59B);
                Wear(mobile, new QuarterStaff(), "Walking Staff", 0x59B);
            };
            Skill(orien, SkillName.Tactics, 80.0);
            Skill(orien, SkillName.Swords, 75.0);
            list.Add(orien);

            WaylanderCharacterDefinition hewla = Allied(Def("hewla", "hewla", "book1", "Hewla", "the mystic", "Independent", "Mystic"));
            hewla.Body = 0x191;
            hewla.Female = true;
            hewla.Hue = Utility.RandomSkinHue();
            hewla.HairItemId = 0x2048;
            hewla.HairHue = 0x47E;
            hewla.Str = 45;
            hewla.Dex = 40;
            hewla.Int = 110;
            hewla.Hits = 120;
            hewla.DamageMin = 4;
            hewla.DamageMax = 8;
            hewla.VirtualArmor = 12;
            hewla.IdentityLine = "Hewla. I prefer truths that can be used over prophecies dressed for a stage.";
            hewla.WaylanderLine = "Waylander listens better than men think when the warning is clean and the ground is killing enough already.";
            hewla.FactionLine = "I belong to my own ground. That is enough.";
            hewla.PhilosophyLine = "Knowledge grows foolish when it starts performing for applause.";
            hewla.Relationships.Add(Rel("dakeyras", "ally", "dry respect", 68, "Waylander is a dangerous man she advises.", WaylanderRelationshipTimelineState.Current, "Waylander is dangerous, yes. So are winter floods. The trick is giving a warning a man can use.", null));
            hewla.Relationships.Add(Rel("kesa_khan", "rival", "spiritual enmity", 20, "Kesa Khan is a rival spiritual force.", WaylanderRelationshipTimelineState.Future, "Kesa Khan walks the spirit world like a general and expects it to salute.", "Book 1 Hewla should not overstate later-book certainty without scenario allowance."));
            hewla.EquipAction = delegate (WaylanderRosterMobile mobile)
            {
                Wear(mobile, new Sandals(), null, 0);
                Wear(mobile, new Robe(), "Mystic Robes", 0x47E);
                Wear(mobile, new QuarterStaff(), "Diviner's Staff", 0x47E);
            };
            Skill(hewla, SkillName.SpiritSpeak, 110.0);
            Skill(hewla, SkillName.Meditation, 100.0);
            list.Add(hewla);

            WaylanderCharacterDefinition kai = Allied(Def("kai", "kai", "book1", "Kai", "the healer", "Independent", "Healer / outcast"));
            kai.Body = 0x190;
            kai.Hue = 0x89F;
            kai.HairItemId = 0x203B;
            kai.HairHue = 0x455;
            kai.Str = 95;
            kai.Dex = 75;
            kai.Int = 90;
            kai.Hits = 165;
            kai.DamageMin = 7;
            kai.DamageMax = 12;
            kai.VirtualArmor = 22;
            kai.IdentityLine = "Kai. I learned early that gentleness is not the same thing as weakness, no matter what frightened people call you.";
            kai.WaylanderLine = "Waylander gave me knives and no pity. That was kindness of a rare sort.";
            kai.FactionLine = "I belong where the wounded still need binding.";
            kai.PhilosophyLine = "The world gives cruelly. That is no excuse to return the habit unchanged.";
            kai.Relationships.Add(Rel("dakeyras", "ally", "grateful loyalty", 90, "Waylander is his benefactor.", WaylanderRelationshipTimelineState.Historical, "Waylander treated me as a man before he treated me as a fighter. I have not forgotten.", null));
            kai.Relationships.Add(Rel("danyal", "ally", "protective", 88, "Danyal is the traveler he protected.", WaylanderRelationshipTimelineState.Historical, "Danyal walked through fear and still kept her kindness. That is harder than steel.", null));
            kai.Relationships.Add(Rel("miriel", "protector", "gentle care", 82, "Miriel is one of the children he protected.", WaylanderRelationshipTimelineState.Historical, "Miriel deserved safety before she ever deserved a blade.", null));
            kai.EquipAction = delegate (WaylanderRosterMobile mobile)
            {
                Wear(mobile, new Sandals(), null, 0);
                Wear(mobile, new Shirt(), "Wilderness Shirt", 0x89F);
                Wear(mobile, new LongPants(), null, 0x89F);
                Pack(mobile, new KaiHuntingKnife(), null, -1);
                Pack(mobile, new KaiHuntingKnife(), null, -1);
                Pack(mobile, new Bandage(40), null, -1);
            };
            Skill(kai, SkillName.Healing, 105.0);
            Skill(kai, SkillName.Anatomy, 85.0);
            Skill(kai, SkillName.Fencing, 70.0);
            list.Add(kai);

            WaylanderCharacterDefinition krylla = Allied(Def("krylla", "krylla", "book1", "Krylla", "the survivor", "Waylander's household", "Civilian"));
            krylla.Body = 0x191;
            krylla.Female = true;
            krylla.Hue = Utility.RandomSkinHue();
            krylla.HairItemId = 0x203C;
            krylla.HairHue = 0x455;
            krylla.Str = 35;
            krylla.Dex = 45;
            krylla.Int = 55;
            krylla.Hits = 85;
            krylla.DamageMin = 2;
            krylla.DamageMax = 5;
            krylla.VirtualArmor = 10;
            krylla.CombatRole = "Protected civilian";
            krylla.IdentityLine = "I am Krylla. Surviving was work enough before anyone started calling it destiny.";
            krylla.WaylanderLine = "Waylander is my father because he chose to be, not because blood demanded it.";
            krylla.FactionLine = "My side is my family.";
            krylla.PhilosophyLine = "Peace is not a small ending. It may be the bravest one some people ever earn.";
            krylla.Relationships.Add(Rel("danyal", "adopted_parent", "love", 100, "Danyal is her adopted mother.", WaylanderRelationshipTimelineState.Current, "Danyal is my mother in every way that matters.", null));
            krylla.Relationships.Add(Rel("dakeyras", "adopted_parent", "love", 96, "Waylander is her adopted father.", WaylanderRelationshipTimelineState.Current, "Waylander taught safety the hard way, but he meant it.", null));
            krylla.Relationships.Add(Rel("miriel", "ally", "twin bond", 98, "Miriel is her twin sister.", WaylanderRelationshipTimelineState.Current, "Miriel is my sister. She runs toward danger faster than I ever cared to.", null));
            krylla.EquipAction = delegate (WaylanderRosterMobile mobile)
            {
                Wear(mobile, new Sandals(), null, 0);
                Wear(mobile, new PlainDress(), null, 0x455);
            };
            Skill(krylla, SkillName.Wrestling, 20.0);
            list.Add(krylla);

            WaylanderCharacterDefinition miriel = Allied(Def("miriel", "miriel", "book2", "Miriel", "Waylander's daughter", "Waylander's household", "Warrior / archer"));
            miriel.Body = 0x191;
            miriel.Female = true;
            miriel.Hue = Utility.RandomSkinHue();
            miriel.HairItemId = 0x2047;
            miriel.HairHue = 0x8A5;
            miriel.Str = 90;
            miriel.Dex = 105;
            miriel.Int = 80;
            miriel.Hits = 160;
            miriel.DamageMin = 9;
            miriel.DamageMax = 14;
            miriel.VirtualArmor = 28;
            miriel.IdentityLine = "Miriel. Waylander taught me enough to keep me alive, and enough to leave marks I still carry.";
            miriel.WaylanderLine = "Waylander is my father and my teacher. I owe him skill, and some grief that came with it.";
            miriel.FactionLine = "I stand with my family first and the Drenai second, which is usually the same war from a different angle.";
            miriel.PhilosophyLine = "Protection means little if it never hardens into mastery. I was not raised to remain helpless.";
            miriel.Relationships.Add(Rel("dakeyras", "adopted_parent", "fierce loyalty", 96, "Waylander is her father and trainer.", WaylanderRelationshipTimelineState.Current, "Waylander taught me to shoot, to cut, and to think past fear. I have spent years deciding what to forgive him for.", null));
            miriel.Relationships.Add(Rel("danyal", "adopted_parent", "love", 98, "Danyal is her adopted mother.", WaylanderRelationshipTimelineState.Current, "Danyal kept us human while harder lessons circled the campfire.", null));
            miriel.Relationships.Add(Rel("krylla", "ally", "twin bond", 100, "Krylla is her twin sister.", WaylanderRelationshipTimelineState.Current, "Krylla reminds me what peace should look like when steel is finally put down.", null));
            miriel.Relationships.Add(Rel("karnak", "enemy", "vengeful hatred", 12, "Karnak becomes her revenge target.", WaylanderRelationshipTimelineState.Future, "Karnak and I belong to a debt that ends in blood if the later years are allowed to stand.", "Early Miriel should not freely recount Book 2 revenge to Book 1 listeners."));
            Fact(miriel, "senta", "Senta was impossible, vain, brave, and far more important to me than he had any right to become.");
            Fact(miriel, "angel", "Angel wore his scars openly enough to make most proud men look theatrical.");
            miriel.EquipAction = delegate (WaylanderRosterMobile mobile) { EquipSimpleLeatherArcher(mobile, "Waylander's Daughter's Jerkin", 0x8A5); Pack(mobile, new Dagger(), "Twin Blade", 0x8A5); Pack(mobile, new Dagger(), "Twin Blade", 0x8A5); };
            Skill(miriel, SkillName.Archery, 100.0);
            Skill(miriel, SkillName.Fencing, 95.0);
            Skill(miriel, SkillName.Tactics, 92.0);
            list.Add(miriel);

            WaylanderCharacterDefinition kesaKhan = Neutral(Def("kesa_khan", "kesa_khan", "book1", "Kesa Khan", "the shaman", "Nadir Wolfshead", "Shaman / commander"));
            kesaKhan.Body = 0x190;
            kesaKhan.Hue = 0x489;
            kesaKhan.HairItemId = 0x203C;
            kesaKhan.HairHue = 0x455;
            kesaKhan.Str = 90;
            kesaKhan.Dex = 75;
            kesaKhan.Int = 110;
            kesaKhan.Hits = 170;
            kesaKhan.DamageMin = 8;
            kesaKhan.DamageMax = 13;
            kesaKhan.VirtualArmor = 26;
            kesaKhan.IdentityLine = "I am Kesa Khan, keeper of the spirit fire and of the bloodline my enemies would cut from the world.";
            kesaKhan.WaylanderLine = "Waylander is a single hunter. I guard a future tribe.";
            kesaKhan.FactionLine = "Wolfshead Nadir. Tribe, bloodline, and spirit do not bow because an empire demands it.";
            kesaKhan.PhilosophyLine = "A generation may bleed so the people endure. The spirit realm is another battlefield, not a refuge from one.";
            kesaKhan.Relationships.Add(Rel("waylander", "enemy", "strategic enmity", 15, "Waylander is his Book 1 enemy.", WaylanderRelationshipTimelineState.Current, "Waylander is dangerous because he thinks like a hunter and not a banner carrier.", null));
            kesaKhan.Relationships.Add(Rel("belash", "ally", "tribal duty", 78, "Belash is his warrior.", WaylanderRelationshipTimelineState.Future, "Belash belongs to the tribe's steel and memory.", "Book 1 Kesa Khan should not casually front-load Book 2 plot unless scenario time allows."));
            kesaKhan.Relationships.Add(Rel("zhu_chao", "faction_enemy", "existential hatred", 5, "Zhu Chao seeks to erase the Wolfshead future.", WaylanderRelationshipTimelineState.Future, "Zhu Chao would murder unborn generations if it bought him one easier century.", "Future-facing context only."));
            kesaKhan.EquipAction = delegate (WaylanderRosterMobile mobile)
            {
                Wear(mobile, new Sandals(), null, 0);
                Wear(mobile, new Robe(), "Shamanic Robes", 0x489);
                Wear(mobile, new QuarterStaff(), "Spirit Staff", 0x489);
            };
            Skill(kesaKhan, SkillName.SpiritSpeak, 110.0);
            Skill(kesaKhan, SkillName.Magery, 95.0);
            Skill(kesaKhan, SkillName.Meditation, 90.0);
            list.Add(kesaKhan);

            WaylanderCharacterDefinition joining = Hostile(Def("joining", "joining", "book1", "Joining", String.Empty, "Shamanic construct", "Hybrid hunter"));
            joining.Aliases = new[] { "joinings" };
            joining.Body = 0x190;
            joining.Hue = 0x47F;
            joining.IsUnique = false;
            joining.AllowMultiples = true;
            joining.CanTalk = true;
            joining.IsHumanoid = true;
            joining.Str = 95;
            joining.Dex = 100;
            joining.Int = 30;
            joining.Hits = 155;
            joining.DamageMin = 8;
            joining.DamageMax = 13;
            joining.VirtualArmor = 20;
            joining.IdentityLine = "Joining. Hunter. Bound to the maker's will until something stronger breaks it.";
            joining.WaylanderLine = "Waylander is prey when the scent is set.";
            joining.FactionLine = "I serve the hand that made the hunt.";
            joining.PhilosophyLine = "Most of us are built for pursuit, not reflection.";
            joining.DefaultReplyLine = "*The creature growls and circles, offering only a broken scrap of meaning.*";
            joining.Relationships.Add(Rel("kesa_khan", "commander", "obedience", 80, "Kesa Khan may command it.", WaylanderRelationshipTimelineState.Current, "Kesa Khan's will is the scent that drives the hunt.", null));
            joining.Relationships.Add(Rel("ustarte", "exception", "confused recognition", 25, "Ustarte is an exceptional Joining with personhood.", WaylanderRelationshipTimelineState.Future, "Ustarte is not like the rest. She stands where most Joinings are only sent.", "Ordinary Joinings should not narrate higher metaphysics cleanly."));
            joining.EquipAction = delegate (WaylanderRosterMobile mobile)
            {
                mobile.Body = Utility.RandomList(0x190, 0x191);
                mobile.Hue = Utility.RandomList(0x47F, 0x489, 0x59C);
                Wear(mobile, new LeatherChest(), "Stitched Hide", mobile.Hue);
                Wear(mobile, new LeatherArms(), null, mobile.Hue);
                Wear(mobile, new Dagger(), "Claw Knife", mobile.Hue);
            };
            Skill(joining, SkillName.Wrestling, 95.0);
            Skill(joining, SkillName.Tactics, 85.0);
            Skill(joining, SkillName.Hiding, 70.0);
            list.Add(joining);

            return list;
        }
    }
}
