namespace Server.Custom.AIGM
{
    public enum AIGMCompanionCapabilityKind
    {
        None,
        Follow,
        Stay,
        Guard,
        ReturnHome,
        TravelReadOnly,
        TravelExecute,
        StopTravel,
        ScanReadOnly,
        ReportThreatsReadOnly,
        ShareAwarenessReadOnly,
        TrackReadOnly,
        TrackingCycle,
        ReportTrackingStatus,
        Attack,
        Disengage,
        Heal,
        Bandage,
        Cure,
        CastHeal,
        CastCure,
        FollowCompanion,
        GreetCompanion,
        AdminCommand,
        Counselor
    }
}
